-- Desktop module graph. Runtime publication uses its own smaller manifest.
return {
    { id = "build.release_check", dependencies = { "build.files", "contracts.json", "contracts.diagnostic" } },
    { id = "build.test_runner", dependencies = {} },
    { id = "build.verify", dependencies = { "build.files", "build.test_runner", "contracts.json", "contracts.diagnostic" } },
    { id = "build.project_init", dependencies = { "build.files", "build.serialize", "converter.inspect", "contracts.json", "contracts.diagnostic" } },
    { id = "build.deploy", dependencies = { "build.files", "contracts.json", "contracts.diagnostic" } },
    { id = "runtime.core.input", dependencies = {} },
    { id = "sdk.schema", dependencies = { "contracts.json", "contracts.diagnostic" } },
    { id = "sdk.menu", dependencies = { "sdk.schema" } },
    { id = "sdk.policy", dependencies = { "sdk.schema", "contracts.diagnostic", "contracts.json" } },
    { id = "sdk.source", dependencies = { "sdk.schema", "contracts.json", "contracts.diagnostic" } },
    { id = "sdk.build", dependencies = { "sdk.schema", "contracts.json", "contracts.diagnostic", "build.bundle" } },
    { id = "sdk.runtime", dependencies = { "sdk.policy", "sdk.menu", "sdk.schema" } },
    { id = "sdk.registry", dependencies = { "sdk.policy", "sdk.build", "sdk.source", "sdk.menu", "sdk.schema", "contracts.json", "contracts.diagnostic", "build.bundle", "build.sha256", "build.serialize" } },
    { id = "runtime.ui.text_limit", dependencies = {} },
    { id = "runtime.ui.message_flow", dependencies = { "runtime.ui.text_limit" } },
    { id = "converter.message", dependencies = { "runtime.ui.message_flow" } },
    { id = "runtime.rpg.map_effects", dependencies = { "runtime.rpg.battle_lifecycle", "runtime.core.rng" } },
    { id = "runtime.ui.name_tables", dependencies = {} },
    { id = "runtime.ui.input_scene", dependencies = { "runtime.ui.name_tables" } },
    { id = "runtime.ui.system_layout", dependencies = {} },
    { id = "platform.ugc.ui_updates", dependencies = { "runtime.ui.text_limit" } },
    { id = "platform.ugc.presentation", dependencies = { "platform.ugc.rpg_windows" } },
    { id = "converter.movement", dependencies = { "contracts.json", "contracts.diagnostic" } },
    { id = "converter.visu_world", dependencies = { "contracts.json", "contracts.diagnostic" } },
    { id = "converter.visu_gameplay", dependencies = { "contracts.json", "contracts.diagnostic" } },
    { id = "converter.visu_locale", dependencies = { "contracts.json", "contracts.diagnostic" } },
    { id = "converter.visu", dependencies = { "converter.visu_world", "converter.visu_gameplay", "converter.visu_locale", "contracts.json", "contracts.diagnostic", "build.files" } },
    { id = "runtime.visu_world", dependencies = {} },
    { id = "runtime.world.movement", dependencies = {} },
    { id = "runtime.presentation", dependencies = {} },
    { id = "runtime.core.timer", dependencies = {} },
    { id = "converter.resources", dependencies = { "contracts.diagnostic", "contracts.json", "converter.message" } },
    { id = "assets.primitive_art", dependencies = { "contracts.diagnostic" } },
    { id = "converter.primitive_art", dependencies = { "build.files", "contracts.diagnostic", "contracts.json", "build.serialize", "assets.primitive_art", "converter.resources", "converter.character_export" } },
    { id = "platform.ugc.map_view", dependencies = {} },
    { id = "platform.ugc.ui_recycle", dependencies = {} },
    { id = "platform.ugc.ui_lifecycle", dependencies = {} },
    { id = "platform.ugc.ui_performance", dependencies = {} },
    { id = "converter.ui_templates", dependencies = { "contracts.json", "contracts.diagnostic" } },
    { id = "converter.map_program", dependencies = { "runtime.world.map", "build.serialize" } },
    { id = "runtime.ui.skill_scene", dependencies = {} },
    { id = "runtime.ui.shop_scene", dependencies = {} },
    { id = "runtime.ui.options_scene", dependencies = {} },
    { id = "runtime.ui.aux_layout", dependencies = {} },
    { id = "converter.audio", dependencies = { "contracts.diagnostic", "contracts.json" } },
    { id = "runtime.audio", dependencies = {} },
    { id = "platform.ugc.audio", dependencies = {} },
    { id = "contracts.diagnostic", dependencies = {} },
    { id = "contracts.json", dependencies = { "contracts.diagnostic" } },
    { id = "contracts.formula", dependencies = {} },
    { id = "vendor.libdeflate", dependencies = {} },
    { id = "assets.png", dependencies = { "vendor.libdeflate" } },
    { id = "assets.tiles", dependencies = { "contracts.json", "contracts.diagnostic" } },
    { id = "assets.characters", dependencies = { "contracts.diagnostic" } },
    { id = "converter.character_export", dependencies = { "assets.characters", "assets.png", "build.files", "contracts.json", "contracts.diagnostic" } },
    { id = "converter.tile_export", dependencies = { "assets.tiles", "assets.png", "build.files", "contracts.json", "contracts.diagnostic", "converter.resources" } },
    { id = "assets.rectframe", dependencies = {} },
    { id = "assets.window_back", dependencies = { "assets.rectframe" } },
    { id = "assets.window_pattern", dependencies = {} },
    { id = "assets.font_sfnt", dependencies = { "vendor.libdeflate" } },
    { id = "assets.font_metrics", dependencies = { "assets.font_sfnt" } },
    { id = "assets.font_outline", dependencies = { "assets.font_sfnt" } },
    { id = "assets.font_layout", dependencies = { "assets.font_sfnt" } },
    { id = "assets.font_layout_proof", dependencies = { "assets.font_sfnt", "build.sha256" } },
    { id = "assets.font_variation", dependencies = { "assets.font_sfnt", "assets.font_metrics", "assets.font_outline" } },
    { id = "assets.font_raster", dependencies = {} },
    { id = "build.serialize", dependencies = { "contracts.json", "contracts.diagnostic" } },
    { id = "build.sha256", dependencies = {} },
    { id = "build.bundle", dependencies = { "contracts.diagnostic", "build.serialize", "build.sha256" } },
    { id = "converter.inspect", dependencies = { "contracts.json", "contracts.diagnostic", "build.sha256" } },
    { id = "converter.events", dependencies = { "converter.message", "converter.movement", "contracts.json", "contracts.diagnostic" } },
    { id = "converter.world", dependencies = { "converter.movement", "contracts.json", "contracts.diagnostic" } },
    { id = "converter.rpg", dependencies = { "contracts.json", "contracts.diagnostic", "contracts.formula" } },
    { id = "converter.ui", dependencies = { "contracts.json", "contracts.diagnostic" } },
    { id = "converter.ui_skin", dependencies = { "assets.png", "assets.rectframe", "build.sha256", "assets.window_back", "assets.window_pattern" } },
    { id = "converter.ui_art", dependencies = { "assets.png", "assets.rectframe", "build.files", "build.sha256", "contracts.diagnostic" } },
    { id = "converter.ui_font", dependencies = { "assets.font_metrics", "assets.font_outline", "build.sha256" } },
    { id = "converter.ui_texts", dependencies = { "contracts.json" } },
    { id = "converter.font_face", dependencies = { "assets.font_metrics", "assets.font_outline", "assets.font_layout", "runtime.ui.font_shaper", "build.sha256" } },
    { id = "converter.font_fallback_face", dependencies = { "assets.font_variation", "assets.font_layout_proof", "build.sha256" } },
    { id = "converter.font_program", dependencies = { "runtime.ui.font_run", "build.serialize" } },
    { id = "converter.actor_program", dependencies = { "runtime.rpg.map_effects", "runtime.rpg.actors", "build.serialize" } },
    { id = "converter.party_program", dependencies = { "runtime.rpg.party", "build.serialize", "contracts.json" } },
    { id = "converter.action_program", dependencies = { "runtime.rpg.action_resolver", "build.serialize" } },
    { id = "converter.enemy_program", dependencies = { "runtime.rpg.enemies", "build.serialize" } },
    { id = "converter.battle_program", dependencies = { "runtime.rpg.battle_lifecycle", "build.serialize" } },
    { id = "runtime.core.state", dependencies = {} },
    { id = "runtime.core.rng", dependencies = {} },
    { id = "runtime.ui.dialogue", dependencies = {} },
    { id = "runtime.ui.rpg_layout", dependencies = { "runtime.ui.message_flow" } },
    { id = "runtime.ui.equip_scene", dependencies = { "runtime.ui.equip_layout" } },
    { id = "runtime.ui.cursor_animation", dependencies = {} },
    { id = "runtime.ui.gauge_layout", dependencies = {} },
    { id = "runtime.ui.extension_scene", dependencies = { "runtime.ui.text_limit" } },
    { id = "runtime.ui.rpg_scene", dependencies = { "runtime.ui.extension_scene", "runtime.core.input", "runtime.ui.message_flow", "runtime.ui.input_scene", "runtime.ui.skill_scene", "runtime.ui.shop_scene", "runtime.ui.options_scene", "runtime.ui.equip_scene", "runtime.ui.battle_scene" } },
    { id = "runtime.ui.menu_layout", dependencies = {} },
    { id = "runtime.ui.equip_layout", dependencies = {} },
    { id = "runtime.ui.battle_scene", dependencies = {} },
    { id = "runtime.ui.battle_layout", dependencies = {} },
    { id = "runtime.ui.item_background", dependencies = { "assets.rectframe" } },
    { id = "runtime.ui.number_text", dependencies = { "runtime.ui.text_raster" } },
    { id = "runtime.ui.text_raster", dependencies = { "assets.font_raster", "assets.rectframe" } },
    { id = "runtime.ui.font_shaper", dependencies = {} },
    { id = "runtime.ui.font_run", dependencies = { "runtime.ui.font_shaper" } },
    { id = "runtime.ui.source_text", dependencies = { "runtime.ui.font_run", "runtime.ui.text_raster" } },
    { id = "runtime.world.events", dependencies = { "runtime.core.state", "runtime.ui.dialogue" } },
    { id = "runtime.world.map", dependencies = {} },
    { id = "runtime.world.camera", dependencies = {} },
    { id = "runtime.world.pages", dependencies = {} },
    { id = "runtime.rpg.party", dependencies = {} },
    { id = "runtime.rpg.traits", dependencies = {} },
    { id = "runtime.rpg.battler_state", dependencies = { "runtime.core.rng" } },
    { id = "runtime.rpg.damage", dependencies = { "contracts.formula", "runtime.core.rng" } },
    { id = "runtime.rpg.action_gate", dependencies = { "runtime.core.rng" } },
    { id = "runtime.rpg.effects", dependencies = { "runtime.core.rng" } },
    { id = "runtime.rpg.action_resolver", dependencies = { "runtime.rpg.action_gate", "runtime.rpg.damage", "runtime.rpg.effects", "runtime.core.rng", "contracts.formula" } },
    { id = "runtime.rpg.enemy_rules", dependencies = { "runtime.rpg.traits", "runtime.core.rng" } },
    { id = "runtime.rpg.battle_targets", dependencies = { "runtime.core.rng" } },
    { id = "runtime.rpg.battle_lifecycle", dependencies = { "runtime.core.rng" } },
    { id = "runtime.rpg.auto_battle", dependencies = { "runtime.core.rng" } },
    { id = "runtime.rpg.battle", dependencies = { "runtime.core.rng", "runtime.rpg.battle_targets", "runtime.rpg.auto_battle" } },
    { id = "runtime.rpg.battle_events", dependencies = { "runtime.core.state", "runtime.world.events", "runtime.ui.dialogue" } },
    { id = "runtime.rpg.enemies", dependencies = { "runtime.rpg.enemy_rules", "runtime.rpg.battler_state", "runtime.rpg.traits", "runtime.core.rng" } },
    { id = "runtime.rpg.actor_rules", dependencies = { "runtime.rpg.traits" } },
    { id = "runtime.rpg.actors", dependencies = { "runtime.rpg.actor_rules", "runtime.rpg.traits", "runtime.core.rng", "runtime.rpg.battler_state" } },
    { id = "runtime.world.session", dependencies = { "runtime.visu_world", "runtime.aurora.game", "runtime.ui.dialogue", "sdk.runtime", "runtime.world.camera", "runtime.core.timer", "runtime.rpg.map_effects", "runtime.world.movement", "runtime.world.map", "runtime.world.pages", "runtime.world.events", "runtime.core.state", "runtime.rpg.party", "runtime.rpg.actors", "runtime.core.rng" } },
    { id = "platform.ugc.event_preview", dependencies = { "runtime.ui.text_limit" } },
    { id = "platform.ugc.rpg_windows", dependencies = { "runtime.ui.text_limit" } },
    { id = "platform.ugc.rpg_preview", dependencies = { "platform.ugc.ui_recycle", "platform.ugc.aurora", "runtime.ui.message_flow", "runtime.ui.system_layout", "platform.ugc.ui_updates", "platform.ugc.presentation", "platform.ugc.map_view", "runtime.ui.aux_layout", "runtime.ui.rpg_scene", "runtime.ui.rpg_layout", "runtime.ui.menu_layout", "runtime.ui.equip_layout", "runtime.ui.battle_layout", "runtime.ui.item_background", "runtime.ui.cursor_animation", "runtime.ui.gauge_layout", "runtime.ui.number_text", "runtime.ui.source_text", "runtime.world.map", "platform.ugc.rpg_windows" } },
    { id = "runtime.ui.world_scene", dependencies = {} },
    { id = "platform.ugc.world_preview", dependencies = { "runtime.ui.text_limit", "runtime.ui.world_scene", "runtime.world.map" } },
    { id = "build.files", dependencies = { "contracts.diagnostic" } },
    { id = "cli", dependencies = {
        "converter.ui_templates", "converter.visu", "converter.aurora", "converter.tile_export",
        "converter.character_export",
        "converter.primitive_art",
        "sdk.registry", "contracts.diagnostic", "contracts.json", "converter.inspect", "converter.events", "converter.audio", "converter.map_program", "converter.resources", "converter.world", "converter.rpg", "converter.ui", "converter.ui_skin", "converter.ui_art", "converter.ui_font", "converter.ui_texts", "converter.font_face", "converter.font_fallback_face", "converter.font_program", "converter.actor_program", "converter.party_program", "converter.action_program", "converter.enemy_program", "converter.battle_program", "runtime.ui.source_text", "runtime.ui.rpg_layout", "runtime.ui.number_text", "runtime.world.session", "build.bundle", "build.files", "build.deploy", "build.project_init", "build.verify", "build.release_check", "build.sha256"
    } },
    { id = "converter.aurora", dependencies = { "converter.character_export", "contracts.json", "contracts.diagnostic", "build.files", "assets.primitive_art" } },
    { id = "runtime.aurora.core", dependencies = {} },
    { id = "runtime.aurora.game", dependencies = { "runtime.aurora.core" } },
    { id = "platform.ugc.aurora", dependencies = { "platform.ugc.rpg_windows" } },
    { id = "runtime.entry", dependencies = { "platform.ugc.ui_performance", "platform.ugc.ui_lifecycle", "runtime.presentation", "runtime.audio", "platform.ugc.audio", "runtime.world.events", "runtime.world.session", "platform.ugc.event_preview", "platform.ugc.world_preview", "platform.ugc.rpg_preview" } },
}
